### ISSUE TITLE
["Request"] use arrow-gradle-config plugins and move to build.gradle.kts

### ISSUE THREAD

**Issue by myuwono** [arrow-kt/arrow-integrations#70]
arrow-integrations will need to be released with the latest arrow-gradle-plugin

**Comment by JavierSegoviaCordoba** [comment]
@i-walker if everything is working correctly with the latest one, we should consider releasing a final version of arrow gradle config, i.e `0.10.0`.

I think Arrow is using the latest correct version so you can check it there in the toml file.

**Comment by i-walker** [comment]
Agree, can we coordinate whether we should publish 0.10.0 before we release arrow or after cc @raulraja, @nomisRev ?

**Comment by nomisRev** [comment]
Arrow Gradle Config lives independently of arrow-kt/arrow since we're already using it in multiple projects.
If Arrow is currently working correctly, then I'm fine releaing a new minor version of Arrow Gradle config 👍

**Comment by i-walker** [comment]
0.10.0 is released - releasing.

**Comment by nomisRev** [comment]
@myuwono we were actually thinking of moving it out of the Arrow repo since we want to only have `Arrow Core`, `Arrow Fx Coroutines` & `Arrow Optics` related things there. We've run into the issue in the past that everything was in a single repo, and this was absolutely not beneficial for maintenance or local development.

I'm working on a document to create an Arrow committee, where contributors & active users of Arrow will be invited to voice their thoughts and get to influence decisions. We're still organizing it, but this could be a great topic for it.
This could be a topic iff discussion there.

**Comment by myuwono** [comment]
ahh i see cool that makes sense! thanks @nomisRev

**Comment by myuwono** [comment]
@i-walker i will need to consult you on this.

**Comment by i-walker** [comment]
Sure, I'll pick this ticket up as soon as possible. Probably end of this week or next week @myuwono
